apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh","-c","env"]
    env:
    - name: MYDBHOST
      valueFrom:
        secretKeyRef:
          name: db-secret
          key:  DBPWD
    - name: MYDBPASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret 
          key:  DBPWD
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
