apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pollarpod
  name: pollarpod
spec:
  containers:
  - image: nginx
    name: pollarpod
    resources: {}
    args:
    - /bin/sh
    - -c
    - curl http://nginxsvc:90 >> /tmp/log.txt ; sleep 1000;
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
