apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: access-pod
  name: access-pod
spec:
  containers:
  - image: ubuntu
    name: access-pod
    command: ["/bin/sh","-c","sleep 5000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
