apiVersion: networking.k8s.io/v1 
kind: NetworkPolicy
metadata:
  name: backendpolicy
spec:
  podSelector:
    matchLabels:
     app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontendapp
    ports:
    - port: 80 
      protocol: TCP
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database
    ports: 
    - port: 80
      protocol: TCP 
     
