apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: frontendpolicy
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
         app: backend
    ports:
    - port: 80
      protocol: TCP
