apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: mappedport 
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
