apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lowlocal
  hostPath:
    path: /Users/sougata/poc/kubevoume 
    type: DirectoryOrCreate
