apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylocalpv
spec:
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 10Mi 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mylocalstore 
  hostPath:
    path: /Users/sougata/poc/localvolume 
