apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: adaptersidecar 
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - name: my-vol
      mountPath: /etc/log
    args:
    - /bin/sh
    - -c 
    - ls > /etc/log/log.txt ; sleep 10;
  - image: busybox
    name: sidecarp
    args:
    - /bin/sh
    - -c
    - cat /etc/log/log.txt ; sleep 5;
    volumeMounts:
    - name: my-vol
      mountPath: /etc/log
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: my-vol
    emptyDir: {}
status: {}
