apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxcanary
  name: nginxcanary
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32005
  selector:
    app: canary
  type: NodePort
status:
  loadBalancer: {}
