apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
spec:
  selector:
    matchLabels:
     envL mypv1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
     storage: 5Mi
  
