apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh","-c","env"]
    env:
    - name: MYKEY1
      valueFrom:
        configMapKeyRef:
          name: simplecm
          key: KEY1
    - name: MYKEY2
      valueFrom:
        configMapKeyRef:
          name: simplecm
          key: KEY2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
