apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh","-c","sleep 500"]
    volumeMounts:
    - name: my-vol
      mountPath: /etc/log/properties
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: my-vol
    configMap:
      name: filecm
status: {}
