apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh","-c","sleep 100"]
    volumeMounts:
    - name: my-vol 
      mountPath: /etc/logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: my-vol
    configMap:
      name: filecm
      items:
        - key: log4j1.properties
          path: log1.properties
        - key: log4j2.properties
          path: log2.properties
status: {}
