apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness
  name: liveness
spec:
  containers:
  - image: registry.k8s.io/liveness
    name: liveness
    resources: {}
    livenessProbe:
      httpGet:
        path: /healtz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awsome
      initialDelaySeconds: 3
      periodSeconds: 3 
    args: 
    - /server
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
