apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: ["/bin/sh", "-c","touch /tmp/healtz; sleep 30 ; rm -f /tmp/healtz ; sleep 600"]
    livenessProbe:
      exec:
        command:
        - cat 
        - /tmp/healtz
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
