apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: CUSTOM
          value: "MY HEADER"
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: READINESS
          value: "READY"
      initialDelaySeconds: 10
      periodSeconds: 6
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 10
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
