apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    livenessProbe:
      exec:
        command:
          - cat 
          - /tmp/myfile
      initialDelaySeconds: 2 
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 5 
    resources: {}
    command: ["/bin/sh","-c","touch /tmp/myfile; sleep 10; rm -f /tmp/myfile; sleep 100"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
