apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
          - name: CUSTOM
            value: CUSTOM
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 4
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
          - name: CUSTOM
            value: CUSTOM
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 4
      timeoutSeconds: 10
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
