apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxblue 
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxblue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxblue
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
