apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po
  name: busybox 
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ["bin/sh","-c" , "ls ; sleep 3600"] 
    resources: {}
  - image: busybox
    name: busybox2
    command: ["bin/sh", "echo Hello World ; /bin/sh/sleep 2600"]
    resources: {}
  - image: busybox
    name: busybox3
    command: ["bin/sh","-c" , " sleep 3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
