apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: multicontainer 
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    args: 
    - /bin/sh
    - -c
    -  while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html;  sleep 5; done
    volumeMounts:
    - name: my-volume
      mountPath: /var/log
  - image: nginx
    name: nginx
    volumeMounts:
    - name: my-volume
      mountPath: /var/log/index.html
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: my-volume
    emptyDir: {}
status: {}
