apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cherry
  name: cherry
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    func: webFrontEnd
  type: NodePort
status:
  loadBalancer: {}
