apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 4 
  selector:
    matchLabels:
      func: webFrontEnd 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        func: webFrontEnd
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
