apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    livenessProbe:
      exec:
        command:
        - ls /tmp/log/log.txt
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
      timeoutSeconds: 5
    readinessProbe:
      exec:
        command:
        - ls /tmp/log/log.txt
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 2
      timeoutSeconds: 5
    args:
    - /bin/sh
    - -c
    - touch /tmp/log/log.txt ; sleep 30 ; rm -f /tmp/log/log.txt; sleep 30;
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
