apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    args:
    - /bin/sh
    - -c
    - echo "Hello Sougata" > etc/logs/logfile.txt ; sleep 5000;
    volumeMounts:
    - name: my-vol
      mountPath: /etc/logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      claimName: mypvc 
status: {}
