apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mylocalstorage
  hostPath:
    path: /Users/sougata/study/ckadpv 
    type: DirectoryOrCreate
